### ISSUE TITLE
Suggestion: create a `pkgdown` style website

### ISSUE THREAD

**Issue by GegznaV** [WinVector/seplyr#1]
I think, your package is a nice initiative. I would like to ask if you mind creating a [`pkgdown`](https://github.com/hadley/pkgdown) style website with online documentation for your package and publishing it as, e.g., [GitHub Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)?

**Comment by MZLABS** [comment]
Good idea, we will try to look into that soonish.

**Comment by JohnMount** [comment]
GregznaV, thanks for the suggestion.  I have started the site: [https://winvector.github.io/seplyr/](https://winvector.github.io/seplyr/).
