### ISSUE TITLE
parse_quosure() was soft-deprecated in rlang 0.2.0

### ISSUE THREAD

**Issue by lionel-** [WinVector/seplyr#3]
Please use `parse_quo()` instead.

**Comment by JohnMount** [comment]
Thanks, Lionel.

I think the `parse_quosure()` code went in in July of 2017 (`rlang` `0.1.1` era, bulk replacing `parse_expr()`).  I'll see if I can bulk-replace it with `parse_quo()` and set an `rlang` version bound.

**Comment by JohnMount** [comment]
Actually is it `parse_quos()` or `parse_quo()`? The help on `rlang` `0.2.2` seems to suggest `parse_quos()`, and I would like to minimize the number of iterations of this run-around.

**Comment by lionel-** [comment]
`parse_quo()` and `parse_expr()` throw an error when there is more than one expression in the string (like `"foo; bar"`). The plural variants return a list of expressions instead (which might be longer than the input character vector).

**Comment by JohnMount** [comment]
I have the changes in.  Is this blocking an `rlang` `CRAN` release, or is this something I can wait on?

**Comment by lionel-** [comment]
Thanks. No hurry, I'm going to wait one more release before deprecating for good. We're also trying out a new soft-deprecation strategy that should be a bit more verbose and make it easier to discover retired functions: Soft-deprecated functions will send a warning once per session when rlang is attached or when the function is called from the global env.

**Comment by JohnMount** [comment]
Okay, thank you for the heads-up. Please do inform me if I have any more soft-deprecated or wrong-choice functions.  I'll clean up such ASAP.

**Comment by lionel-** [comment]
With the dev version of rlang you can also set `options(lifecycle_force_verbose_retirement = TRUE)` and then run your tests to find out. This option forces the warnings.
