### ISSUE TITLE
group_summarize fails is groupvingVars is empty

### ISSUE THREAD

**Issue by ftobin** [WinVector/seplyr#4]
`mtcars %>% group_summarize(c(), mpg=mpean(mpg))` fails because internal functional variable 'dg' is not set in this codepath.  Same if groupingVars is NULL.

**Comment by JohnMount** [comment]
Sorry about that, my fault.  And thank you very much for filing an issue.  I have fixed it in the development version ( [ref](https://github.com/WinVector/seplyr/commit/0143355ce86965be270445e0d781a81f1ccc0ade)), but can not release to CRAN until they re-open their submission queue in early January ( [ref](https://stat.ethz.ch/pipermail/r-package-devel/2018q4/003293.html) ).

``` r
library("seplyr")
#> Loading required package: wrapr

group_summarize(mtcars, c(), mpg=mean(mpg))
#>        mpg
#> 1 20.09062
```
